// This file is auto-generated by the Python script.
const metrics = {
    r2: 0.8397,
    adjR2: 0.8387,
    mae: 2007.82,
    rmse: 2881.50,
    lastUpdated: "October 26, 2023, 5:45 PM" // Example date, will be generated by Python
};